export const sections = [
  {
    title: "Para você",
    items: [
      {
        icon: "/icons/menu/streak.svg",
        bg: "#3a1518",
        title: "Meu Streak",
        subtitle: "leitura da edição",
        path: "#",
      },
      {
        icon: "/icons/menu/podcasts-menu.svg",
        bg: "#241b33",
        title: "Podcasts",
        subtitle: "biblioteca de episódios",
        badge: "NOVO",
        path: "/podcasts",
      },
      {
        icon: "/icons/menu/discussoes.svg",
        bg: "#211d14",
        title: "Discussões",
        subtitle: "fórum e debates do dia",
        path: "#",
      },
      {
        icon: "/icons/menu/jogos.svg",
        bg: "#221c33",
        title: "Jogos",
        subtitle: "Palavritas, Teia e mais",
        badge: "NOVO",
        path: "#",
      },
    ],
  },
  {
    title: "Conteúdo",
    items: [
      {
        icon: "/icons/menu/noticias.svg",
        bg: "#16242b",
        title: "Notícias",
        subtitle: "feed personalizado de notícias",
        path: "#",
      },
      {
        icon: "/icons/menu/edicoes-anteriores.svg",
        bg: "#15211c",
        title: "Edições Anteriores",
        subtitle: "histórico de newsletters",
        path: "#",
      },
      {
        icon: "/icons/menu/agenda.svg",
        bg: "#2e1410",
        title: "Agenda",
        subtitle: "calendário de newsletters",
        badge: "NOVO",
        path: "#",
      },
    ],
  },
  {
    title: "Social & Diversão",
    items: [
      {
        icon: "/icons/menu/comunidade.svg",
        bg: "#2c1a26",
        title: "Comunidade",
        subtitle: "feed social de livros",
        path: "#",
      },
      {
        icon: "/icons/menu/copitas.svg",
        bg: "#142219",
        title: "Copitas",
        subtitle: "palpita classificados e vencedores",
        path: "#",
      },
      {
        icon: "/icons/menu/buscar-pessoas.svg",
        bg: "#1c2436",
        title: "Buscar pessoas",
        subtitle: "encontre leitores por nome ou @",
        path: "#",
      },
      {
        icon: "/icons/menu/evento.svg",
        bg: "#341621",
        title: "Evento seis&seis",
        subtitle: "saiba mais sobre o evento",
        path: "#",
      },
    ],
  },
  {
    title: "Conta",
    items: [
      {
        icon: "/icons/menu/perfil.svg",
        bg: "#16213a",
        title: "Meu Perfil",
        subtitle: "configurações da conta",
        path: "#",
      },
      {
        icon: "/icons/menu/notificacoes.svg",
        bg: "#2e2410",
        title: "Notificações",
        subtitle: "central de notificações",
        path: "#",
      },
      {
        icon: "/icons/menu/cupons.svg",
        bg: "#142420",
        title: "Cupons",
        subtitle: "descontos exclusivos para você",
        path: "#",
      },
      {
        icon: "/icons/menu/presente.svg",
        bg: "#241c33",
        title: "Presente",
        subtitle: "ganhe recompensas indicando amigos",
        badge: "GANHE PRÊMIOS",
        path: "#",
      },
      {
        icon: "/icons/menu/bloqueados.svg",
        bg: "#341417",
        title: "Usuários bloqueados",
        subtitle: "gerenciar quem você bloqueou",
        path: "#",
      },
      {
        icon: "/icons/menu/onboarding.svg",
        bg: "#142420",
        title: "Rever Onboarding",
        subtitle: "replay do onboarding interativo",
        path: "#",
      },
    ],
  },
  {
    title: "Entre em Contato",
    items: [
      {
        icon: "/icons/menu/ajuda.svg",
        bg: "#332410",
        title: "Ajuda",
        subtitle: "central de suporte",
        path: "#",
      },
      {
        icon: "/icons/menu/email.svg",
        bg: "#16213a",
        title: "E-mail",
        subtitle: "app@thenews.com.br",
        path: "#",
      },
      {
        icon: "/icons/menu/site.svg",
        bg: "#191c3a",
        title: "Site The News",
        subtitle: "thenews.com.br",
        path: "#",
      },
      {
        icon: "/icons/menu/instagram.svg",
        bg: "#2c1a26",
        title: "Instagram",
        subtitle: "@thenewscc",
        path: "#",
      },
    ],
  },
];
